"""Dependency-injection contracts for federation transport and key management."""
from __future__ import annotations

from typing import Protocol


class FederationSigner(Protocol):
    def sign(self, payload: bytes, key_id: str) -> bytes: ...
    def verify(self, payload: bytes, signature: bytes, key_id: str) -> bool: ...


class KeyProvider(Protocol):
    def active_key_id(self, node_id: str) -> str: ...
    def public_key_fingerprint(self, key_id: str) -> str: ...


class FederationTransport(Protocol):
    def send(self, peer_node: str, payload: bytes) -> None: ...
    def receive(self) -> bytes | None: ...
    def close(self) -> None: ...
